#!/bin/sh

usage() {
  echo "Usage: ./build.sh <network_interface_names> [<base_i3_config_path> <i3blocks_disk_config> <has_battery>]"
}

[ -z "$1" ] && printf "Please provide the name of your network interface!\n" && usage && exit 1
NETWORK_INTERFACES=$1

APPLICATION_THEMES_DIR=application-themes

if [ -z "$2" ]; then
  BASE_I3_CONFIG_PATH=$APPLICATION_THEMES_DIR/i3/base/config.base
else
  BASE_I3_CONFIG_PATH=$2
fi

if [ "$3" = "1" ]; then
  I3BLOCKS_DISK_CONFIG_PATH=$APPLICATION_THEMES_DIR/i3/base/disk_i3blocks.conf
else
  I3BLOCKS_DISK_CONFIG_PATH=$3
fi

HAS_BATTERY=$4

COMPILE_DIR=compiled-theme
GTK3_DIR=gtk-3.0
GTK2_DIR=gtk-2.0
ASSETS_DIR=assets

rm -rf $COMPILE_DIR
mkdir -p $COMPILE_DIR/gtk/$GTK3_DIR/
sassc -t compact $GTK3_DIR/main.scss $COMPILE_DIR/gtk/$GTK3_DIR/gtk.css
sassc -t compact $GTK3_DIR/app-specific.scss $COMPILE_DIR/gtk/$GTK3_DIR/app-specific.css
cp -r $GTK2_DIR $COMPILE_DIR/gtk
cp -r $ASSETS_DIR $COMPILE_DIR/gtk
cp -r $APPLICATION_THEMES_DIR $COMPILE_DIR

I3BLOCKS_CONF_PATH=${COMPILE_DIR}/${APPLICATION_THEMES_DIR}/i3/i3blocks.conf
sed -i -e "s\{{HOME_DIR}}\\${HOME}\g" $I3BLOCKS_CONF_PATH

DISK_ENTRIES=$(cat "${I3BLOCKS_DISK_CONFIG_PATH}" 2>/dev/null | tr "\n" "@")
sed -i -e "s%{{DISK_ENTRIES}}%${DISK_ENTRIES}%" $I3BLOCKS_CONF_PATH

I3_DIR=${COMPILE_DIR}/${APPLICATION_THEMES_DIR}/i3

if [ -n "${HAS_BATTERY}" ]; then
  BATTERY_CONFIG_PATH=${I3_DIR}/conditional-configs/battery.conf
  BATTERY_ENTRY=$(cat "${BATTERY_CONFIG_PATH}" 2>/dev/null | tr "\n" "@")
fi

sed -i -e "s#{{BATTERY}}#${BATTERY_ENTRY}#" $I3BLOCKS_CONF_PATH

I3BLOCKS_CONF=$(sed -e "s%{{NETWORK_INTERFACES}}%${NETWORK_INTERFACES}%" $I3BLOCKS_CONF_PATH)

echo "$I3BLOCKS_CONF" | tr "@" "\n" >$I3BLOCKS_CONF_PATH

COMPILED_I3_CONFIG=${COMPILE_DIR}/${APPLICATION_THEMES_DIR}/i3/config

echo "##################################
###### GENERATED BY MONSTER ######
# PLEASE EDIT THE BASE CONFIG AND
# RE-BUILD RATHER THAN EDITING
# THIS FILE
# Base config: ${BASE_I3_CONFIG_PATH}
# Disk config: ${I3BLOCKS_DISK_CONFIG_PATH}
##################################" >${COMPILED_I3_CONFIG}

cat ${BASE_I3_CONFIG_PATH} >>${COMPILED_I3_CONFIG}

echo "##################################
###### GENERATED BY MONSTER ######
# ANYTHING ABOVE COMES FROM THE
# BASE CONFIG.
# Base config: ${BASE_I3_CONFIG_PATH}
# Disk config: ${I3BLOCKS_DISK_CONFIG_PATH}
#
# (EDIT THERE NOT HERE)
#
# ANYTHING BELOW THIS LINE IS
# GENERATED BY MONSTER
##################################" >>${COMPILED_I3_CONFIG}

for file in ${I3_DIR}/partial-configs/*; do
  if [ -f "$file" ]; then
    config=$(cat "$file")
    printf "${config}\n" >>${COMPILED_I3_CONFIG}
  fi
done

echo "##################################
###### GENERATED BY MONSTER ######
# EDIT BASE CONFIG NOT HERE
# Base config: ${BASE_I3_CONFIG_PATH}
# Disk config: ${I3BLOCKS_DISK_CONFIG_PATH}
##################################" >>${COMPILED_I3_CONFIG}

sed -i -e "s\{{HOME_DIR}}\\${HOME}\g" $COMPILED_I3_CONFIG

zip -q ${COMPILE_DIR}/${APPLICATION_THEMES_DIR}/firefox/theme.zip ${COMPILE_DIR}/${APPLICATION_THEMES_DIR}/firefox/manifest.json
